### ISSUE TITLE
Forking is not working 

### ISSUE THREAD

**Issue by RockStarMe** [scormaq/gradle-serenity-cucumber-forking#1]
Hi @scormaq ,

I am trying to execute two feature files using forking but what I observed now all scenarios are **not** executed. So the test was started but after launching browser it's not executing all scenarios from my test. However, if I execute a single file then it's working fine.

**Comment by scormaq** [comment]
Hi @RockStarMe , thanks for attention :)
This project may be stale since I published it - Serenity and Cucumber both evolved a bit. However if you did not change anything and just used steps from README demo section, you should see the same result as I - all forked runners are used.

Can you share your project and give more info about your problem? Maybe I can help you with it. Also it is useful to specify next:
* versions of cucumber & Serenity;
* the way you launch browser;
* OS/java/etc

P.S. I personally do not use forking mechanizm because it messes up console logging (and I just don't like to deal with multithreading). In my work I use only batching.

Edit: just realized that your issue might be related to absence of `glue` package in configuration 🙂 So forking worked, but cucumber itself was unable to map feature file to definition methods.

I updated the project (and also updated serentiy & cucumber versions to latest versions). Please try them and let me know about results. 👋

**Comment by RockStarMe** [comment]
Hi @scormaq ,

No, I don't have any issue with glue code and I am able resolved execution issue. I think there is an issue with implementation because when I am trying to execute my test with forking on the local & remote browser it's not executing all feature file.

        dc.setCapability(CapabilityType.BROWSER_NAME, BrowserType.CHROME);
        dc.setCapability(CapabilityType.PLATFORM, Platform.ANY);
        dc.setCapability("accessKey", ACCESS_KEY);
        dc.setCapability("testName", "XXXXX");

serenity-cucumber=1.9.31
serenity_version = "2.0.40"

**Comment by dipakbachhav** [comment]
Hi @scormaq : Can you please confirm if I need to use cucumber 4 for given forking solution? if so, currently I am using cucumber datatable in my test and I think cucumber 4 is not supporting datatable.

**Comment by scormaq** [comment]
hi @dipakbachhav ,
Thanks for interest to my project. Please refer to [official Serenity documentation](https://serenity-bdd.github.io/theserenitybook/latest/serenity-parallel-batches.html) to get all the details about forking serenity-cucumber project. My project is a simple adaptation of existing mechanizm to Gradle.

As I can see, there is 1.9.16-SNAPSHOT version of serenity-cucumber in documentation above, which actually should depend on cucumber 2.4.0. So I can say that both cucumber2 and cucumber4 are effectively suitable for this.

**Comment by scormaq** [comment]
Hi @RockStarMe ,
I think you should expect bunch of problems when bring multi-threading or other kind of parallelization into your project. There can be problems with browser instantiation (like in your case(, or access to static stuff, or race condition etc. Also there is known problem with console logging - all logs become messed up, because they being printed in the same time. That is why I personally try to avoid forking.

Regarding your problem, I would recommend to use some selenium grid, or more modern containerized solutions like Selenoid, Zalenium or dockerized Selenium grid. I use [Selenoid](https://github.com/aerokube/selenoid), it is pretty easy to set up and configure, and it can support up to 5 parallel browser sessions.

**Comment by dipakbachhav** [comment]
I am actually trying to achieve cross-browser testing using serenity but before that I thought to implement parallelization. Sorry but I am not so happy with your forking implementation as it's not so much effective.

**Comment by nkilin** [comment]
Hi @scormaq, first off great work with the implementation since your way is the only way I managed to correctly execute the Serenity forking mechanism with Cucumber JVM via gradle.
Problem is that once you switched **serenity-cucumber** with **serenity-cucumber4** (and force _io.cucumber:cucumber-core:4.2.0_ etc.) the forking no longer works.

If I run **"gradle clean test aggregate -Dserenity.fork.count=2"** using your initial commit everything works as intended. The generated [Serenity report](https://i.imgur.com/97n4vdK.png) shows the scenarios were executed run on two threads as intended. [Intellij](https://i.imgur.com/JZHfu7h.png) shows this properly as well.

If I run the same command using your latest commit please see the generated[ Serenity report](https://i.imgur.com/rf4arFZ.png). Notice that there are no longer 10 scenarios, there are only 5. The Serenity slicing mechanism is triggered, but both threads will execute the same scenario as shown in [Intellij](https://i.imgur.com/rfZCCIT.png) as well.

This must be because the "**serenity.fork.number**" property is no longer ingejcted correctly from **SerenityCucumberForker**. I am quite curious how (if) we could resolve this.

**Comment by scormaq** [comment]
Hi @nkilin ,
Thanks for comment, good catch! Indeed, execution was broken with migration from cucumber2 to cucumber4, because of changes in Cucumber listener mechanizm. As I aware, for Cucumber 4+ version all plugins (listeners) have to implement not `cucumber.api.formatter.Formatter` but `cucumber.api.event.ConcurrentEventListener`, otherwise there will be problems with parallel execution.

I pushed changes, now it should work as before.

**Comment by nkilin** [comment]
Awesome! In the meantime with some trial and error I managed to use the same fix, although didn't have the time to properly test it out. Thanks for the fast reply and update, keep up the good work! :)

Edit: At this point I think this issue can be closed.

**Comment by sudarsunperu** [comment]
Hi @scormaq 
Thank you so much for this. I'm trying to execute Runners in parallel using Gradle. But I'm trying to make the Runners run in Parallel threads and not separate JVMs. 

I've implemented the same using Maven Surefire Plugin and trying to replicate the same using Gradle. Can you please let me know if it is possible with the approach that you have designed?

I'm sending the threadCount from commandline and each thread starts a *Runner.java
I'm trying to replicate the below maven configuration in Gradle

**Maven configuration**
```
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.0.0-M3</version>
				<configuration>
					<includes>
						<include>**/*Runner.java</include>
					</includes>
					<parallel>classes</parallel>
					<threadCount>${parallel.tests}</threadCount>
					<forkCount>1</forkCount>
					<perCoreThreadCount>false</perCoreThreadCount>
				</configuration>
			</plugin>
```

**Comment by scormaq** [comment]
Hi @sudarsunperu ,
I don't have an experience to parallel tests in threads within same JVM... I also doubt that suite slicing mechanizm was designed for it - you might face unpredictable race condition errors, I personally do not recommend to use it.

Regarding your question, here what I know so far:
AFAIK gradle does not have capability to generate multiple threads within same JVM ([link](https://discuss.gradle.org/t/how-to-run-junit-tests-in-1-jvm-but-with-multiple-threads/32652)). Such mechanizm should be implemented with test framework instead.
As I know, you can parallel pure Cucumber tests using `--threads` flag, but I didn't use it, and - once again - I doubt that it will work correctly with suite slicing mechanizm.

P.S. Do you really need parallelization through threads? You can just increase count of forks, or batches.

**Comment by sudarsunperu** [comment]
Hi @scormaq 
Thank you for your response. I'm trying to run ~200 test cases using Selenoid. They test a Web Application, which requires to login into the application. To avoid overlap between the executions when running in parallel, i want each execution to pick a unique loginCredentials.
In the Current implementation, we have a synchronized method which provides unique LoginCredentials upon each invocation. So all ~200 invocations, will receive unique LoginCredentials

The problem with increasing the fork to more than 1 is that, the each JVM has its own synchronized method and hence duplicate LoginCredentials are issued. 

I really like the idea of using batches, but I havent used it before.

**Comment by scormaq** [comment]
@sudarsunperu well, so it sounds like a problem with shared test data pool. You just need to find a way make credentials truly unique. For example, knowing number of forks and bactches, you can add batch number and fork number to credentials, then during test launch each slice of test will pick their own part.

**Comment by sudarsunperu** [comment]
@scormaq 
Thanks for your help. I'll try to design a solution using batchs to make the credentials unique.

**Comment by przemyslawbiesek** [comment]
Hi @scormaq 

I just updated my serenity and cucumber versions to
    compile "net.serenity-bdd:serenity-core:2.1.5"
    compile "net.serenity-bdd:serenity-cucumber4:2.1.2"
    compile "io.cucumber:cucumber-core:4.8.0"
    compile "io.cucumber:cucumber-junit:4.8.0"
    compile "io.cucumber:cucumber-java:4.8.0"

But I'm getting the same results as described by @sudarsunperu .
Can you help me with that

**Comment by scormaq** [comment]
Hi @przemyslawbiesek ,
sorry but I didn't get your problem. As discussed above, I am not aware about applying multithreading to Gradle.
In my opinion, multithreading has same effect as forking JVMs - it allows to parallel tests within same computer instance, but forking is easier to implement and more safe (as it prevents race conditions over static variables).
If you'd like to describe your goal in detail, we can discuss it further.

**Comment by przemyslawbiesek** [comment]
Sorry
I just noticed that the problem with results only from one fork on the report was reported my @nkilin :)
My bad

**Comment by przemyslawbiesek** [comment]
@scormaq  So long story short with the newest version on the Serenity BDD test report I'm getting results only from one fork - so I think this is the same problem as described by @nkilin.  Do you have an idea what can be the cause of it ?

**Comment by scormaq** [comment]
@przemyslawbiesek you're right, there is issue with latest versions. The solution with cucumber plugin does not work anymore, because now slicing mechanizm happens _before_ modifying serenity fork properties in plugin, so effectively every fork executes same slice of tests.

I introduced another solution which fixes this issue - a bit clumsy, but it works well. Now it does not depend on gradle properties. Check latest `master` for details.

**Comment by przemyslawbiesek** [comment]
Thanks Pavlo

Have you maybe ever tried to run those parallel tests on Jenkins ? Before (on older version of cucumber and serenity ) it was working ok but right now I’m getting empty report. I checked the logs and tests are run but report is empty
[cid:image001.png@01D5F136.D1558B30]

I checked it locally and it is not repoducible

Przemysław Biesek | Senior Test Engineer | Kainos
E: p.biesek@kainos.com | W: www.kainos.com<http://www.kainos.com>

Facebook<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2FKainosSoftware%2F&data=02%7C01%7CP.Biesek%40kainos.com%7C596bca0330fc442af6eb08d76118136c%7C7ed9bdc7964d4dc09084812b90e05c6d%7C0%7C0%7C637084628391516055&sdata=NlNDnc3Qh6JEgCJpX6CMEOl7SgopbqXH1F5074SnlZ0%3D&reserved=0> | LinkedIn<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fkainos%2F&data=02%7C01%7CP.Biesek%40kainos.com%7C596bca0330fc442af6eb08d76118136c%7C7ed9bdc7964d4dc09084812b90e05c6d%7C0%7C0%7C637084628391526048&sdata=Ijd%2F3vIyScuPLnSqYFnm66LRf1xpCoy5ZpjX1x5q1zo%3D&reserved=0> | Twitter<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FKainosSoftware&data=02%7C01%7CP.Biesek%40kainos.com%7C596bca0330fc442af6eb08d76118136c%7C7ed9bdc7964d4dc09084812b90e05c6d%7C0%7C0%7C637084628391536037&sdata=X7FYYBimd%2BZfjC%2BVonRi0l3%2Feq7iibFRnPunUB6X5Ao%3D&reserved=0>

**Comment by scormaq** [comment]
@przemyslawbiesek I'm running tests in parallel on gitlab CI using latest approach I described earlier, and there no issues with reporting. 

In updated readme of this project you can also find [screenshots](https://github.com/scormaq/gradle-serenity-cucumber-forking/raw/master/images) of generated serenity report - as shown, all scenarios reported.
